# Generated by Django 5.0.3 on 2024-04-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='url',
        ),
    ]
