# Generated by Django 5.0.3 on 2024-04-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_service', '0002_rename_description_item_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.CharField(max_length=16),
        ),
    ]
