# Generated by Django 5.0.3 on 2024-04-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_service', '0003_alter_item_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.CharField(max_length=46),
        ),
    ]
