FROM python:3.11.1
ENV PYTHONUNBUFFERED 1
WORKDIR /bscatalogservice
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY . ./
EXPOSE 6060
EXPOSE 8000
CMD ["python", "manage.py", "runserver"]