name: Build and test Python app - BasketSaver

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main']
  
jobs:
  test:
      name: Test
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - name: Setup Environment variables
            run: |
              mv BasketSaverUserService/.env.example BasketSaverUserService/.env
              mv BasketSaverCatalogService/.env.example BasketSaverCatalogService/.env
              mv BasketSaverGroceryListService/.env.example BasketSaverGroceryListService/.env

          - uses: actions/setup-python@v4
            with:
              python-version: '3.9'

          - name: Building backend docker images
            run: |
              docker compose -f docker-compose-testing.yaml up -d
          
          - name: Waiting for containers
            run: |
              sleep 60s
          - name: Running unit tests
            run: |
              docker ps
              docker exec userservice python manage.py test
              
          - name: Installing NPM
            uses: actions/setup-node@v2
            with:
              node-version: '16.x'
          - name: Running workers
            run: |
              docker exec --detach catalogservice python BasketSaverCatalogService/BasketSaverCatalogService/manage.py start_worker
              docker exec --detach groceryservice python BasketSaverGroceryListService/BasketSaverGroceryListService/manage.py start_worker
          - name: Populating DB
            run: |
              docker exec groceryservice python BasketSaverGroceryListService/BasketSaverGroceryListService/manage.py gen-stores
              docker exec catalogservice python BasketSaverCatalogService/BasketSaverCatalogService/manage.py populate_db_testing
            continue-on-error: true
          - name: Installing Newman
            run: |
              docker ps
              npm i newman -g
          - name: Running Integration Tests
            run: | 
              docker ps
              newman run Individual.postman_collection.json
            continue-on-error: true
          - name: Logging
            run: |
              docker logs userservice
              docker logs groceryservice
              docker logs catalogservice
