name: Build and test Python app - BasketSaver

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main']
  
jobs:
  test:
      name: Test
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - name: Setup Environment variables
            run: |
              mv BasketSaverUserService/.env.example .env
              mv BasketSaverCatalogService/.env.example .env
              mv BasketSaverGroceryListService/.env.example .env
          - uses: actions/setup-python@v4
            with:
              python-version: '3.9'

          - name: Building backend docker images
            run: |
              ls .
              ls BasketSaverUserService/
              ls BasketSaverCatalogService/
              ls BasketSaverGroceryListService/
              docker compose up -d
          
          - name: Waiting for containers
            run: |
              sleep 5s
          - name: Running unit tests
            run: |
              docker ps
              docker exec userservice python manage.py test
